In [2]:
l = [23245, 27, 546, 215,  -1234]

In [3]:
l

[23245, 27, 546, 215, -1234]

In [4]:
import numpy as np

In [5]:
 a = np.array(l)

In [6]:
a

array([23245,    27,   546,   215, -1234])

In [7]:
b = np.array([12,455, 63.3, True, 'abc'])

In [8]:
print(b)

['12' '455' '63.3' 'True' 'abc']


In [9]:
l.pop()

-1234

In [10]:
l

[23245, 27, 546, 215]

In [11]:
a.mean()

4559.8

In [14]:
l[0:2]

[23245, 27]

In [15]:
l[::2]

[23245, 546]

---

# Slicing Arrays

In [16]:
a

array([23245,    27,   546,   215, -1234])

In [18]:
a[2:]

array([  546,   215, -1234])

In [19]:
a[2:4]
# with arrays you are not creating another array

array([546, 215])

In [20]:
b = a[2:4]

In [21]:
b

array([546, 215])

In [22]:
b[0]

546

In [24]:
b[:] = 111

In [25]:
b

array([111, 111])

In [26]:
a

array([23245,    27,   111,   111, -1234])

In [28]:
c = a.copy()

In [29]:
c

array([23245,    27,   111,   111, -1234])

In [30]:
a

array([23245,    27,   111,   111, -1234])